Update error message

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -58,7 +58,7 @@ find_program() {
     fi
   done
 
-  echo "Unable to find any of the following: $@" 1>&2
+  echo "Unable to find any file: $@" 1>&2
   set -e
   exit 1
 }
